# Generated by Django 3.1.3 on 2021-08-12 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('parcial1', models.FloatField()),
                ('parcial2', models.FloatField()),
                ('parcial3', models.FloatField()),
                ('promedio', models.FloatField()),
            ],
        ),
    ]
